export const DOMINANT_SPEAKER_CHANGED = 'DOMINANT_SPEAKER_CHANGED';
export const PARTICIPANT_JOINED = 'PARTICIPANT_JOINED';
export const PARTICIPANT_LEFT = 'PARTICIPANT_LEFT';
export const PARTICIPANT_PINNED = 'PARTICIPANT_PINNED';
export const PARTICIPANT_UPDATED = 'PARTICIPANT_UPDATED';
