export const PARTICIPANT_ADDED = 'PARTICIPANT_ADDED';
export const PARTICIPANT_REMOVED = 'PARTICIPANT_REMOVED';
export const PARTICIPANT_PINNED = 'PARTICIPANT_PINNED';
export const PARTICIPANT_ROLE_CHANGED = 'PARTICIPANT_ROLE_CHANGED';
export const DOMINANT_SPEAKER_CHANGED = 'DOMINANT_SPEAKER_CHANGED';
export const PARTICIPANT_VIDEO_STARTED = 'PARTICIPANT_VIDEO_STARTED';