export const DOMINANT_SPEAKER_CHANGED = 'DOMINANT_SPEAKER_CHANGED';
export const PARTICIPANT_ADDED = 'PARTICIPANT_ADDED';
export const PARTICIPANT_FOCUSED = 'PARTICIPANT_FOCUSED';
export const PARTICIPANT_PINNED = 'PARTICIPANT_PINNED';
export const PARTICIPANT_REMOVED = 'PARTICIPANT_REMOVED';
export const PARTICIPANT_SELECTED = 'PARTICIPANT_SELECTED';
export const PARTICIPANT_UPDATED = 'PARTICIPANT_UPDATED';
