export const JITSI_CLIENT_CONNECTED = 'JITSI_CLIENT_CONNECTED';
export const JITSI_CLIENT_CREATED = 'JITSI_CLIENT_CREATED';
export const JITSI_CLIENT_DISCONNECTED = 'JITSI_CLIENT_DISCONNECTED';
export const JITSI_CLIENT_ERROR = 'JITSI_CLIENT_ERROR';
export const JITSI_CONFERENCE_JOINED = 'JITSI_CONFERENCE_JOINED';
export const RTC_ERROR = 'RTC_ERROR';